In [19]:
root = "C:/Users/v-wangwilli/projects/nepas"
setwd(root)
.libPaths(file.path(root, "renv/library/windows/R-4.4/x86_64-w64-mingw32"))

library(jsonlite)
library(tidyverse)

source("script/processors.R")

Attaching package: 'jsonlite'


The following object is masked from 'package:purrr':

    flatten

# Manual cleaning steps

- Changed order of Nassau-Suffolk in 1972, page 18, line 66 to put OUTSIDE CENTRAL CITIES line last

In [20]:
years = 1967:1979

bps_cleaned = map(
  years,
  \(year) process_year(year, root = "data/cleaned_ocr/")
) |> bind_rows()

bps = add_smsa_indicators(bps_cleaned)

# Name cleaning
- corrected obvious typographical errors or inconsistencies
- took largest geographical area when possible --> combined multiple rows in earlier files
- aligned state abbreviations

To-do:
- fuzzy matching to see if didn't missed any inclusions

In [ ]:
bps = bps |>
  mutate(
    smsa_name_clean = smsa_name |>
      str_remove_all("[0-9]|\\.|\\*|#") |>
      str_replace_all(" *- *", "-") |>
      str_squish() # Remove whitespace from ends and turn multiple spaces into one
  )

bps_smsa = bps |>
  filter(smsa_indicator == 1)

smsa_names = bps_smsa |>
  summarize(.by = smsa_name_clean, smsa_name = str_c(unique(smsa_name), collapse = " | "), line_number = first(line_number), year = first(year), page_numbers = first(page_numbers)) |>
  arrange(smsa_name_clean)

# write_csv(smsa_names, "derived_data/summaries/smsa_names.csv")

In [ ]:
smsa_name_mapping = read_csv("derived_data/mappings/smsa_name_mapping.csv")

bps_corrected = bps_smsa |>
  left_join(smsa_name_mapping, join_by(smsa_name_clean)) |>
  summarize(
    .by = c(smsa_name_corrected, year),
    across(total_units:public_valuation, \(col) sum(col, na.rm = TRUE))
  ) |>
  separate_wider_delim(smsa_name_corrected, delim = ", ", names = c("central_city", "state"), cols_remove = FALSE)

states = bps_corrected |>
  distinct(state) |>
  arrange(state)

# write_csv(states, "derived_data/summaries/states.csv")

Rows: 377 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): smsa_name_clean, smsa_name_corrected

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [31]:
state_mapping = read_csv("derived_data/mappings/state_mapping.csv")
state_adoption = read_csv("derived_data/state_adoption.csv")

bps_final = bps_corrected |>
  left_join(state_mapping, join_by(state)) |>
  mutate(states = state_corrected, primary_state = str_sub(state_corrected, 1, 2)) |>
  separate_longer_delim(state_corrected, delim = "-") |>
  left_join(state_adoption, join_by(state_corrected == state)) |>
  summarize(
    .by = c(smsa_name_corrected:public_valuation, states, primary_state),
    adoption_year = adoption_year |> replace_na(Inf) |> min(na.rm = TRUE)
  ) |>
  mutate(
    event_year = year - adoption_year,
    treat = as.numeric(event_year > -1)
  ) |>
  rename(smsa = smsa_name_corrected)

Rows: 81 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): state, state_corrected

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 17 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): state
dbl (1): adoption_year

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [35]:
head(bps_final)

write_csv(bps_final, "data/cleaned_ocr/bps_final.csv")

  smsa                              year total_units private_total
1 ABILENE, TEX                      1967  247         247
2 AKRON, OHIO                       1967 4732        4732
3 ALBANY, GA                        1967  472         472
4 ALBANY-SCHENECTADY-TROY, NY       1967 3309        3309
5 ALBUQUERQUE, NMEX                 1967 1334        1334
6 ALLENTOWN-BETHLEHEM-EASTON, PA-NJ 1967 3172        3172
  private_1_unit private_2_units private_3_4_units private_5plus_units
1   95             2               0                150
2 2289           540             159               1744
3  339            71               0                 62
4 1985           312             107                905
5  827             6              17                484
6 1831            28              19               1294
  public_units private_structures ⋯ private_1_unit_val private_2_units_val
1 0              6                ⋯  1929                14
2 0            106                ⋯ 48831              5734
3 0             11                ⋯  4627               278
4 0             70                ⋯ 36164              3015
5 0             13                ⋯ 15703                43
6 0             83                ⋯ 32094               323
  private_3_4_units_val private_5plus_units_val public_valuation states
1    0                   1380                   0                TX
2 1567                  18478                   0                OH
3    0                    430                   0                GA
4 1260                   6254                   0                NY
5  117                   3466                   0                NM
6  171                   8284                   0                PA-NJ
  primary_state adoption_year event_year treat
1 TX             Inf          -Inf       0
2 OH             Inf          -Inf       0
3 GA            1991           -24       0
4 NY            1975            -8       0
5 NM             Inf          -Inf       0
6 PA            1989           -22       0

# Missingness exploration

In [36]:
bps_final |>
  count(smsa) |>
  count(n)

Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.

   n  nn
1   1   6
2   2   5
3   3   6
4   5  11
5   6   3
6   7   7
7   9  32
8  11   3
9  12 120
10 13  99

In [37]:
bps_final |>
  count(year)

   year n
1  1967 225
2  1968 227
3  1969 227
4  1970 100
5  1971 260
6  1972 260
7  1973 263
8  1974 264
9  1975 271
10 1976 271
11 1977 276
12 1978 277
13 1979 283

In [59]:
bps_13balanced = bps_final |>
  filter(.by = smsa, n() == 13)

In [62]:
expand_grid(
  bps_final |> filter(.by = smsa, n() == 12) |> distinct(smsa),
  year = 1967:1979
) |>
  anti_join(
    bps_final |> filter(.by = smsa, n() == 12),
    join_by(smsa, year)
  ) |>
  count(year)

  year n
1 1970 120

The MSAs with only one year missing are all missing 1970, the atypically small sample.